require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'example/**/*.rb'

Layout/LineLength:
  Max: 120

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - test/**/*.rb

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/Void:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/ParallelAssignment:
  Enabled: false

Style/Semicolon:
  Exclude:
    - test/**/*.rb

Style/SingleLineMethods:
  Enabled: false

Style/MapToSet:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - test/**/*.rb

Naming/VariableName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/bcdd-contract.rb

Metrics/BlockLength:
  Exclude:
    - bcdd-contract.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/bcdd/contract.rb

Metrics/AbcSize:
  Exclude:
    - lib/bcdd/contract.rb
    - lib/bcdd/contract/list.rb
    - lib/bcdd/contract/map/pairs.rb
    - lib/bcdd/contract/map/schema.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/bcdd/contract.rb
    - lib/bcdd/contract/list.rb
    - lib/bcdd/contract/map/pairs.rb
    - lib/bcdd/contract/map/schema.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/bcdd/contract.rb
    - lib/bcdd/contract/map/pairs.rb
    - lib/bcdd/contract/map/schema.rb

Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertEmptyLiteral:
  Enabled: false

Minitest/AssertOperator:
  Enabled: false

Performance/RedundantBlockCall:
  Exclude:
    - lib/bcdd/contract.rb
